CategoryMaster.create!(id: 1, name: '食費', is_common: true)
CategoryMaster.create!(id: 2, name: '日用雑貨', is_common: true)
CategoryMaster.create!(id: 3, name: '通信', is_common: true)
CategoryMaster.create!(id: 4, name: '水道・光熱', is_common: true)
CategoryMaster.create!(id: 5, name: '住まい', is_common: true)
CategoryMaster.create!(id: 6, name: 'エンタメ', is_common: true)
CategoryMaster.create!(id: 7, name: '大型出費', is_common: true)
CategoryMaster.create!(id: 8, name: 'その他', is_common: true)

CategoryMaster.create!(id: 9, name: '交通', is_common: false)
CategoryMaster.create!(id: 10, name: '交際費', is_common: false)
CategoryMaster.create!(id: 11, name: '教育・教養', is_common: false)
CategoryMaster.create!(id: 12, name: '医療・保険', is_common: false)
CategoryMaster.create!(id: 13, name: '美容・衣服', is_common: false)