version: '3'
services:
  web:
    build: ./
    command: tail -f /dev/null
#    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    ports:
      # ruby-debug-ide 用
      - "1234:1234"
      - "26162:26162"
      # rails用
      - "3000:3000"
    depends_on:
      - db
    volumes:
      - ./:/usr/src/household_account_book
    environment:
      RAILS_ENV: development
      DATABASE_URL: postgres://postgres@db:5432
    tty: true
    stdin_open: true
  db:
    image: postgres:12.2
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: household_account_book_development
      POSTGRES_HOST_AUTH_METHOD: trust
