version: '3'
services:
  web:
    build: ./
    command: tail -f /dev/null
    ports:
    - 3000:3000
    depends_on:
    - db
    volumes:
    - ./:/usr/src/household_account_book
    environment:
      RAILS_ENV: development
      DATABASE_URL: postgres://postgres@db:5432
    tty: true
    stdin_open: true
  db:
    image: postgres:10.1-alpine
    ports:
    - 5432:5432
    environment:
      POSTGRES_DB: household_account_book_development
