default: &default
  site_name: PairMoney
  selection_year_term: 30
  slack_webhook_url: https://hooks.slack.com/services/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
  production_url: https://pairmoney.herokuapp.com
  demo_url: https://demo-pairmoney.herokuapp.com

development:
  <<: *default

test:
  <<: *default

staging:
  <<: *default

demo:
  <<: *default

production:
  <<: *default
