default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: household_account_book_development

test:
  <<: *default
  database: household_account_book_test

staging:
  <<: *default
  database: staging_household_account_book

production:
  <<: *default
  database: household_account_book_production
  username: household_account_book
  password: <%= ENV['HOUSEHOLD_ACCOUNT_BOOK_DATABASE_PASSWORD'] %>
